### ISSUE TITLE
Grafana-Direktlinks auf den link-Info-Seiten

### ISSUE THREAD

**Issue by ghost** [FreifunkBremen/meshviewer#11]
Bei den Node-Infos [1] haben wir Direktlinks zu Grafana, weil die Diagramme langsamer (oder garnicht) laden.
Das Gleiche hätte ich gerne bei den Link-Infos [2]. 

[1] https://map.bremen.freifunk.net/#!/en/map/ec086bf8fa6c
[2] https://map.bremen.freifunk.net/#!/en/map/ec086bf8fa6c-a42bb0b0f1ae

**Comment by genofire** [comment]
ggf. als Image Button, wie bei https://karte.freifunk-owl.de/#!/en/map/83bd979b9499
![a](https://user-images.githubusercontent.com/6905586/56340172-68fc9480-61b1-11e9-9f72-5612fdb35694.png)

Hat wer Lust ein Button image zu designen?

Oder nehmen wir einfach direkt das Grafana Logo:
![](https://i0.wp.com/www.neteye-blog.com/wp-content/uploads/2017/12/Grafana.png)

**Comment by genofire** [comment]
solved ... so besser?
