### ISSUE TITLE
Branch chaos

### ISSUE THREAD

**Issue by genofire** [FreifunkBremen/meshviewer#3]
Wollen wir die andren branche weghauen (abgesehen von `master` und später `release` pull/2).
Wenn wir unser eigenes foo machen, würde ich ungern nicht fertige Sachen weiterentwickeln.

**Comment by genofire** [comment]
????
(würde nun gerne die Graphen von influxdb einbauen)

**Comment by jplitza** [comment]
Von welchen Branches genau redest du? Du entwickelst auf master, oder? Meinetwegen können die Upstream-Branches (dev und filter) weg, die gibts ja da auch noch. Aber alles andere ist doch von dir selbst!?

**Comment by genofire** [comment]
Gut dann räume ich auf
