### ISSUE TITLE
[BUG] links don't disappear when filtering nodes

### ISSUE THREAD

**Issue by SimJoSt** [FreifunkBremen/meshviewer#4]
## Expected Behavior

When one or both nodes from a link have been filtered either by the nodes or the statistics I would expect the link to disappear as well.

## Current Behavior

In Bremen the links don't disappear when one or both nodes have been filtered which makes for a very weird picture when most nodes have been hidden.
Only applies to the Bremen setup. Regensburg is not affected.

## Steps to Reproduce (for bugs)

1. open map
2. go to statistics tab or use the node filter
3. apply a filter which only affects one side/node of a link AND not the links itself (`online`/`offline`)
4. watch buggy magic

**Comment by SimJoSt** [comment]
Upon further testing I discovered, that using the `online` and `offline` filters is not suitable for this bug, as links have the value `online` or `offline` themselves and the filter applies to them directly.
A better fit would be to apply the "not shown on map" filter. As you can see, even when both nodes are missing, the link is still painted. This apparently also applies to the node filter

I updated the issue accordingly.

**Comment by genofire** [comment]
Thank you for reporting and sorry for the delay of answer.
Still exists this bug?

**Comment by genofire** [comment]
@SimJoSt

**Comment by SimJoSt** [comment]
I tested the problem again with the described steps to reproduce, but couldn't notice any abnormal behaviour anymore.
