### ISSUE TITLE
Neuen Tag setzen

### ISSUE THREAD

**Issue by oliver** [FreifunkBremen/meshviewer#5]
Unter http://bremen.freifunk.net/meshviewer/ ist noch die letzte getaggte Version v4 im Einsatz. Seitdem sind ein paar kleinere Fixes dazugekommen (https://github.com/FreifunkBremen/meshviewer/compare/v4...FreifunkBremen:master).
Spricht was dagegen, die aktuelle Version zu taggen und unter http://bremen.freifunk.net/meshviewer/ zu installieren?

**Comment by Timi7007** [comment]
+1
IMO spricht nichts gegen den Einsatz der aktuellen Version, genau dafür haben wir die ja. Ich würde es begrüßen, wenn die Änderungen gemacht werden, da gerade auf mobilen Endgeräten die roten, blinkenden Punkte ganz schön laggen können. Da auf dem alten Server das gleiche Konstrukt schon einmal lief, denke ich, dass sich eventuelle Probleme in Grenzen halten würden.

**Comment by genofire** [comment]
-2 (glaub @jplitza ist meiner, folgender Meinung)
Es befinden sich viele Änderungen bereits upstream im dev branch.
Dadurch wird ein Versionswechsel (bei einer neuen Meshviewer Version) von unseren Fork schlecht möglich sein.
Unser Fork war nur eine temporäre Lösung.
(Unsere Änderungen wie das Blinken sollten in einer vernünftigen Form gebracht werden und upstream zur Verfügung gestellt werden. - Vernünftig heißt, das man das Blinken in der Konfigurationsdatei einstellen kann, sodass diese Funktionalität nicht verloren/ersetzt sondern erweitert wird.)

Nebenbei technischer Sicht: Das Blinken ist per CSS gelöst und nicht mit Javascript.
Dies sollte sich nur geringfügig auf die Performance des Browser auswirken

**Comment by jplitza** [comment]
Da ich in den Kommentaren zu 6d0143dcc25b38f4fc58090f566e3cbf1c3dfdab im Wesentlichen das selbe gesagt habe, bin ich natürlich @genofire's Meinung was das Taggen angeht. Allerdings ist dieses Repo schon irgendwie dafür gedacht, auf dem Webserver zu laufen.

**Comment by Timi7007** [comment]
Ok, nach den Hinweisen stimme ich euch zu.
Wie siehst da mit dem Upstream aus? Ist da ein Release in Sicht?
Wollen wir bis zu einem Release im Upstream vielleicht einfach die aktuelle Version dieses Repos wieder auf dem Webserver laufen lassen?

@genofire Was das Blinken angeht: Natürlich hast du Recht, aber ich hab da so ein Windows 8.1 Tablet und da IE als einziges eine richtige Touchunterstützung hat... Das sieht halt schon doof aus ;D

**Comment by jplitza** [comment]
Upstream wird momentan nicht wirklich weiterentwickelt, also wird es da auch nicht so bald ein Release geben. Und ich schrieb ja schon, dass ich dafür bin unser Repo aufm Webserver laufen zu lassen.

**Comment by SimJoSt** [comment]
Da wir in Zukunft auf dem [Regensburger-Fork](https://github.com/ffrgb/meshviewer) setzen wollen, kann dieses Issue geschlossen werden.

**Comment by genofire** [comment]
True
